# Generated by Django 4.0.2 on 2022-02-06 19:11

from django.db import migrations, models
import storefront.utils


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_add_zip_to_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='expires_at',
            field=models.DateTimeField(default=storefront.utils.get_expiration),
        ),
    ]
